name: Deploy VitePress docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CF_DISTRIBUTION_ID: ${{ vars.CF_DISTRIBUTION_ID }}
  ROLE_ARN: ${{ vars.ROLE_ARN }}
  BUILD_DIR: ${{ vars.BUILD_DIR }}
  CSP_NONCE: ${{ secrets.CSP_NONCE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: |
            **/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: |
          npm run docs:build 2>/dev/null || npx vitepress build
        env:
          BUILD_NONCE: ${{ env.CSP_NONCE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Sync to S3
        run: |
          aws s3 sync "${BUILD_DIR}" "s3://${S3_BUCKET}" \
            --delete --no-progress

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CF_DISTRIBUTION_ID}" \
            --paths "/*"
